### ISSUE TITLE
Unable to Build Book Locally

### ISSUE THREAD

**Issue by imeMFK01** [NeuromatchAcademy/course-content#961]
Hi,

I am receiving below errors while building a book locally. So, based on **Error 1**, I can see **tutorials/static/nma-logo-square-4xp.png** and its location but unable to locate this "intro.rst " which is **Error 2**.

(python3NMA) E:\NMA\Course-Content-ComputationalNeuroscience>jupyter-book build book
Running Jupyter-Book v0.10.2
Source Folder: E:\NMA\Course-Content-ComputationalNeuroscience\book
Config Path: E:\NMA\Course-Content-ComputationalNeuroscience\book\_config.yml
Output Path: E:\NMA\Course-Content-ComputationalNeuroscience\book\_build\html
←[01mRunning Sphinx v3.5.4←[39;49;00m
**←[91mWARNING: logo file 'tutorials/static/nma-logo-square-4xp.png' does not exist←[39;49;00m**
←[91mWARNING: favicon file 'tutorials/static/nma-logo-square-4xp.png' does not exist←[39;49;00m
←[01mmyst v0.13.7:←[39;49;00m MdParserConfig(renderer='sphinx', commonmark_only=False, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, update_mathjax=True, enable_extensions=['amsmath', 'dollarmath', 'html_image', 'substitution'], disable_syntax=[], url_schemes=['mailto', 'http', 'https'], heading_anchors=None, html_meta=[], footnote_transition=True, substitutions=['open_access', 'closed_access'], sub_delimiters=['{', '}'])
←[01mbuilding [mo]: ←[39;49;00mtargets for 0 po files that are out of date
←[01mbuilding [html]: ←[39;49;00mtargets for 0 source files that are out of date
←[01mupdating environment: ←[39;49;00m[new config] 0 added, 0 changed, 0 removed

←[91mSphinx error:←[39;49;00m
**master file E:\NMA\Course-Content-ComputationalNeuroscience\book\tutorials\intro.rst not found**
Traceback (most recent call last):
  File "e:\NMA\python3nma\lib\site-packages\jupyter_book\sphinx.py", line 150, in build_sphinx
    app.build(force_all, filenames)
  File "e:\NMA\python3nma\lib\site-packages\sphinx\application.py", line 352, in build
    self.builder.build_update()
  File "e:\NMA\python3nma\lib\site-packages\sphinx\builders\__init__.py", line 298, in build_update
    len(to_build))
  File "e:\NMA\python3nma\lib\site-packages\sphinx\builders\__init__.py", line 310, in build
    updated_docnames = set(self.read())
  File "e:\NMA\python3nma\lib\site-packages\sphinx\builders\__init__.py", line 421, in read
    self.env.doc2path(self.config.master_doc))
sphinx.errors.SphinxError: master file E:\NMA\Course-Content-ComputationalNeuroscience\book\tutorials\intro.rst not found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\DoctorStrange\AppData\Local\Schrodinger\PyMOL2\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\DoctorStrange\AppData\Local\Schrodinger\PyMOL2\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\NMA\python3NMA\Scripts\jupyter-book.exe\__main__.py", line 7, in <module>
  File "e:\NMA\python3nma\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "e:\NMA\python3nma\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "e:\NMA\python3nma\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "e:\NMA\python3nma\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "e:\NMA\python3nma\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "e:\NMA\python3nma\lib\site-packages\jupyter_book\commands\__init__.py", line 305, in build
    result, builder, OUTPUT_PATH, build_type, PAGE_NAME, click.echo
  File "e:\NMA\python3nma\lib\site-packages\jupyter_book\commands\__init__.py", line 546, in builder_specific_actions
    raise RuntimeError(_message_box(msg, color="red", doprint=False)) from result
RuntimeError:
←[91m===============================================================================←[0m

Your help will be highly appreciable.

Looking forward.

Thanks.

**Comment by spirosChv** [comment]
@imeMFK01 Have you followed all steps from here? https://github.com/NeuromatchAcademy/course-content/blob/main/book/README.md
